### ISSUE TITLE
Improved TLS security with imported DH keys

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#133]
**Reported by iulius on 27 Dec 2008 15:58 UTC**
nnrpd currently uses precomputed ephemeral Diffie-Hellman keys.  It should support user-specified files, to eliminate risk of "small group" attacks.

**Comment by rra** [comment]
**Modified by iulius on 27 Dec 2008 16:06 UTC**

**Comment by ewxrjk** [comment]
nnrpd (or rather OpenSSL) always uses ephemeral keys. The things that are fixed are the domain parameters, and they are fixed to RFC7917 safe prime groups. These are impractical to attack by construction (and also FIPS-140 compliant, on the offchance any INN users cared about that l-)

Personally I would leave the code as it stands.

**Comment by Julien-Elie** [comment]
Yes we have pre-defined DH groups as suggested in Appendix A of RFC 7919, of 2048, 4096 and 8192 bits.
We recently got rid of weaker groups, fortunately :)

This ticket is because of the comment
`FIXME:  support user-specified files, to eliminate risk of "small group" attacks.`
in the source code.  Instead of using `PEM_read_bio_DHparams` with these hard-coded groups, it would have been to use `PEM_read_DHparams` in external files (which would by default contain these hard-coded groups).

I guess very few people, if any, will dare change them anyway...
So you're right that this ticket may be closed as won't fix and the FIXME line changed to something else (like they are "impractical to attack by construction and also FIPS-140 compliant" and will be changed in future INN releases in case they are no longer considered secure).  I can do that if that's OK for you too.

**Comment by ewxrjk** [comment]
Yes, I think a comment about the origin of the groups is sufficient.

**Comment by Julien-Elie** [comment]
Reopening this issue because OpenSSL 3.0.0 has deprecated `PEM_read_bio_DHparams` and `SSL_CTX_set_tmp_dh_callback`.

> Applications may supply their own DH parameters instead of using the built-in values. This approach is discouraged and applications should in preference use the built-in parameter support described above.

Seems like all we now need is:

`SSL_CTX_set_dh_auto(CTX, 1);`

And all the rest can be removed (callback and hard-coded DH groups in our source code.)
Would then it be OK?

**Comment by ewxrjk** [comment]
That sounds good. It looks like it's supported in OpenSSL 1.1.1 too, and it will give us the RFC3526 safe prime groups.

**Comment by Julien-Elie** [comment]
Looking at OpenSSL code, it is even present in 1.1.0 (though their man pages were only updated for 1.1.1).
