### ISSUE TITLE
Files missing from Github repo resulting in compilation failures

### ISSUE THREAD

**Issue by jahway603** [InterNetNews/inn#274]
I'm reporting this issue as I am not able to build/compile INN using either the Github repo or the Github source releases. Both the [Github repo](https://github.com/InterNetNews/inn) & [Gihub source releases](https://github.com/InterNetNews/inn/releases) are missing certain files which do exist in the [source code releases from the ISC website](https://ftp.isc.org/isc/inn/), such as `configure` and `include/config.h.in` -- the ISC source code release is building/compiling and has these files which are missing from the Github.

Also, the [Arch Linux package](https://gitlab.archlinux.org/archlinux/packaging/packages/inn/-/blob/main/PKGBUILD) does build/compile INN successfully, but [it is using the source code from ISC, as seen on Line 61](https://gitlab.archlinux.org/archlinux/packaging/packages/inn/-/blob/main/PKGBUILD#L61)

Can these missing files, which are required to build/compile INN, be included in this Github repo?

**Comment by Julien-Elie** [comment]
When building directly from the GitHub sources, you have to run the following commands first (see [BOOTSRAP])(https://github.com/InterNetNews/inn/blob/main/BOOTSTRAP)):

```
    ./autogen
    ./configure
    make bootstrap
```

Alternatively, if you do not want to bootstrap the sources, you can use [the daily generated snapshots](https://ftp.isc.org/isc/inn/snapshots/daily/) which contain the latest source with the bootstrapped files like `configure`.

**Comment by jahway603** [comment]
Thank you for this @Julien-Elie. I was able to successfully build inn from this github repo, but I used `make` instead of `make bootstrap`.

**Comment by Julien-Elie** [comment]
`make bootstrap` will essentially generate the documentation.
I think the missing step was for you `./autogen`.  Once run, you can `./configure` and just run the usual `make` command.  It will generate the documentation at the same time it builds INN.

**Comment by jahway603** [comment]
Much appreciated! I was able to create the [Arch Linux AUR inn-git package](https://aur.archlinux.org/packages/inn-git) for people who want to run the bleeding edge INN.

**Comment by Julien-Elie** [comment]
Good to know!  Thanks for having packaged the latest version of INN!

If I may suggest:

```
[innd.service]
Description=Inetnet News Daemon
```

There's a typo in the name of INN.  Also, if you wish to add more parameters, you can have a look at the [init systemd sample](https://github.com/InterNetNews/inn/blob/main/contrib/sample.init.systemd).


Why not just use `news` instead of IDs?  Aren't they define in the system?  (Why not create them instead, if not present?)
It would notably save you the change in `config.h`:

```
	--with-news-user=9 \
	--with-news-group=13
  # See https://wiki.archlinux.org/index.php/DeveloperWiki:UID_/_GID_Database
  test -f include/config.h
  cat >>include/config.h <<EOF
#undef RUNASUSER
#define RUNASUSER "news"
#undef RUNASGROUP
#define RUNASGROUP "news"
EOF
```


It seems that there is no default crontab shipped with the package.  Couldn't one be added at least with `news.daily`, `rnews -U`, `sendinpaths` (along with the appropriate _inpaths!_ flush) and a regular flushing of cached IP addresses (reloading _incoming.conf_)?

There also are useful dependencies to install which do not seem to be present (like gnupg, libcanlock which is in AUR, zlib).
