### ISSUE TITLE
Latest git pull fails to build

### ISSUE THREAD

**Issue by nelgin** [InterNetNews/inn#277]
make[1]: Entering directory '/usr/compile/inn/site'
/bin/bash ./getsafe.sh ../samples/newsfeeds newsfeeds
../samples/newsfeeds newsfeeds differ: byte 5199, line 125
../samples/newsfeeds has changed; please update newsfeeds
make[1]: *** [Makefile:289: newsfeeds] Error 1
make[1]: Leaving directory '/usr/compile/inn/site'
make: *** [Makefile:70: all] Error 1

**Comment by Julien-Elie** [comment]
You're not building from a fresh checkout.
You should remove the previously generated samples (INN warns at build time when they've changed since the last build).

```
cd site
make distclean
cd ..
make
```

**Comment by nelgin** [comment]
Can this be documented in INSTALL so I don’t have to try and remember to do it or as part of the build process when doing a make update ?

**Comment by Julien-Elie** [comment]
Would a different output like that suit you?
(One will directly know what happens, especially with the diff result, and may not have seen the related the one line in the whole INSTALL doc.)


```
/bin/bash ./getsafe.sh ../samples/newsfeeds newsfeeds
../samples/newsfeeds newsfeeds differ: byte 3242, line 71
--- ../samples/newsfeeds	2023-08-06 11:08:47.898941607 +0200
+++ newsfeeds	2023-08-06 11:08:46.418911469 +0200
@@ -68,7 +68,7 @@
 ##  name of the host to feed articles to; without "-y" an innfeed.conf
 ##  file is needed.
 
-# innfeed funnel master.  Comment change!
+# innfeed funnel master.
 #innfeed!\
 #    :!*\
 #    :Tc,Wnm*:/home/news/bin/innfeed
../samples/newsfeeds has changed; please update newsfeeds
When taken into account, "rm site/newsfeeds" and continue the build
To silent all the changes, run "cd site && make distclean"
make[2]: *** [Makefile:289 : newsfeeds] Error 1
make[2] : Leaving directory « /home/news/work/inn/main/site »
make[1]: *** [Makefile:70 : all] Error 1
```

**Comment by nelgin** [comment]
Maybe, but if the system knows there are new samples, why wouldn’t it just update itself? I don’t see why it wouldn’t.

Are you expecting the user to manually diff between site and samples to see what is new? It’s really not clear what the intentions of this are, unless it’s listed further down the install which I didn’t read at that point because I was only updating.

**Comment by Julien-Elie** [comment]
When running `make update`, the new samples are not installed (otherwise it would remove your _inn.conf_, _newsfeeds_, _readers.conf_, etc. files).
This message during the build is to let you know that there has been a change in the upstream samples since the last time you built the source code.  If you're interested in backporting them to your own installed files in production, then it's time to.
We can't install them, it's just a reminder of the changed that may be interesting to look at.

**Comment by Julien-Elie** [comment]
After all, I am unsure anyone cares about that current build error saying the samples have changed.
I would finally be inclined to just go on building INN instead of bailing out.  The message would still be output but it would no longer result in a fatal exit.
It would solve the problem you're facing.

**Comment by Julien-Elie** [comment]
Enhancement done in 97bff2d37a062c70f9f9361050d3e86f59395fc9.
