### ISSUE TITLE
Support throttling control message processing

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#99]
**Reported by eagle on 15 Dec 2008 00:52 UTC**
This doesn't seem to have been a problem recently as much, but when there are a lot of control messages, INN's behavior is less than ideal.  Each processed control message causes all feeds to be closed and reopened, which often leaves orphaned innfeed spools since innfeed's lock management doesn't handle the case well.

This is a patch from F. Senault <fred@lacave.net> that makes controlchan batch changes and, if too many come in during a short period, will throttle innd before making all the changes at once.  This forces all feeds to only be closed and reopened once.

- [controlchan.diff.txt](https://github.com/InterNetNews/inn/files/6835406/controlchan.diff.txt)

**Comment by rra** [comment]
**Comment by iulius on 15 Dec 2008 20:41 UTC**
For that patch to work fine, "ctlinnd changegroup" should be possible when the news server is throttled.  (Changes of moderation status would otherwise be impossible.)

According to the man page of ctlinnd:

"This command, unlike newgroup or rmgroup, can only be used while the server is running, and will be rejected if the server is paused or throttled."

**Comment by rra** [comment]
**Modified by iulius on 16 Jan 2010 20:46 UTC**

**Comment by rra** [comment]
**Modified by iulius on 2 Apr 2015 18:49 UTC**

**Comment by rra** [comment]
**Comment by iulius on 31 Jul 2016 20:08 UTC**
Milestone renamed

**Comment by Julien-Elie** [comment]
I would tend to close this bug because its rationale was the presence of orphaned **innfeed** dropped files.  Frédéric proposed this patch in 2008 because of that (and at that time it is true there were more control articles than nowadays).
Since then, **news.daily** has been improved and calls **procbatch** to process such dropped files, if present.  So the issue is no longer a real problem.

I'll close it in a few months if nobody speaks up.
